const WORDS = [
  "adabu", "agano", "agiza", "ahadi", "ajira", "akiba", "akili", "ambia",
  "amini", "amkia", "amsha", "amuka", "amani", "angua", "anika", "ardhi",
  "arifu", "asali", "augua", "azima", "baada", "bahia", "bando", "bangi",
  "bango", "barua", "benki", "bichi", "bidii", "bisha", "bofya", "boksi",
  "bomba", "bomoa", "bonge", "bwana", "bunge", "bwawa", "bwege", "bweta",
  "chafu", "chaka", "chake", "chako", "chama", "chana", "chapa", "chati",
  "chaza", "cheka", "cheko", "cheua", "cheza", "chini", "chipu", "choka",
  "choma", "chora", "chota", "choyo", "chuja", "chuki", "chuma", "chuna",
  "chupa", "chura", "daawa", "dagaa", "daiwa", "danda", "dengu", "dhama",
  "dhana", "dhani", "dhati", "dhifa", "dhiki", "dhobi", "dhulu", "dimba",
  "dimbi", "dingi", "diraa", "dobia", "doria", "dumaa", "dunda", "dunia",
  "elewa", "elimu", "embe", "endea", "eneza", "epuka", "erevu", "faida",
  "fagia", "fagio", "faini", "fanya", "fedha", "fensi", "fidia", "fingo",
  "finya", "finyo", "fuata", "fukia", "fukua", "fuma", "fumba", "fumbo",
  "fumua", "funda", "fundi", "funga", "fungo", "fungu", "funua", "funza",
  "funzo", "fursa", "futia",  "fyata", "fyeka", "ganda", "ganga",
  "gango", "genge", "geuka", "geuza", "ghafi", "ghali", "ghati", "gombe",
  "gombo", "gonga", "gunda", "gundi", "gunia", "gunzi", "hiana", "hiari",
  "hicho", "huria", "hukmu", "ibada", "idadi", "idhaa",
  "igiza", "ijara", "ijayo", "ikulu", "ilani", "imamu", "imani", "imara",
  "inama", "ingia", "inika", "inuka", "itika", "itiko", "jalia", "jamaa",
  "jamii", "jambo", "jamvi", "janga", "jasho", "jazia", "jazwa", "jembe",
  "jenga", "jengo", "jeuri", "jicho", "jidai", "jimbi", "jinsi", "jipya",
  "jipu", "jitu", "jumba", "jumla", "jungu", "kabla", "kaidi", "kalio",
  "kamba", "kambi", "kambo", "kamua", "kanda", "kando", "kanga", "kania",
  "kanwa", "kanzu", "karao", "kasha", "kasia", "kataa", "kauka", "kauli",
  "kemea", "kenda", "kenge", "kenua", "kesha", "kesho", "kidau", "kifua",
  "kijia", "kijio", "kilio", "kinga", "kingo", "kisha", "kocha", "kochi",
  "kofia", "kojoa", "koleo", "kombe", "komoa", "konda", "konde", "kondo",
  "konga", "konzi", "kosha", "kubwa", "kucha", "kumba", "kumbe", "kumbi",
  "kumbo", "kunde", "kundi", "kunga", "kunya", "kunzi", "kwale", "kwama",
  "kwani", "kwapa", "kwata", "kwaya", "kweza", "kweli", "laana", "labda",
  "ladha", "laini", "laiti", "lakia", "lalia", "lamba", "laumu", "lazwa",
  "legea", "lemea", "lengo", "liana", "limao", "linda", "linga", "lipia",
  "lisha", "longa", "lugha", "lunda", "madai", "mafua", "mamba", "maoni",
  "maono", "makao", "mamia", "mango", "mazao", "mbale", "mbali", "mbaya",
  "mbegu", "mbele", "mbinu", "mbivu", "mboga", "mbona", "mbuzi", "mbuyu",
  "mechi", "mende", "mengi", "menya", "mfano", "mfuko", "mfupa", "mgeni",
  "miayo", "milia", "mjini", "mkali", "mkate", "mkeka", "mkono", "mkopo",
  "mkufu", "mlima", "mnara", "mnene", "mpira", "mpole", "msala", "msitu",
  "mtoto", "mungu", "munyu", "muozo", "mvuke", "mvivu", "mwana", "mwaka",
  "mwasi", "mwaza", "mwema", "mwezi", "mwiba", "mwiko", "mwili", "mwitu",
  "mwiza", "mzazi", "mzigo", "mzimu", "mzozo", "mzuka", "mzuri", "mzizi",
  "nabii", "nadra", "nafaa", "nafuu", "nanas", "nanua", "nauli", "nawia",
  "ndama", "ndani", "ndevu", "ndimi", "ndimu", "ndizi", "ndogo", "ndoto",
  "ndowa", "ndugu", "nduma", "nenda", "ngapi", "ngano", "ngao", "ngazi",
  "ngeli", "ngili", "ngoma", "ngome", "ngoja", "ngono", "nguvu", "nguzo",
  "nidha", "njiwa", "njozi", "njuga", "nukta", "nyaka", "nyama", "nyasi",
  "nyati", "nyavu", "nyayo", "nyoka", "nyota", "nyuma", "nzige", "ogopa",
  "okoka", "okota", "olewa", "ombea", "onana", "ondoa", "oneka", "onewa",
  "ongea",  "pakia", "pakua", "palia", "pamba", "panda",
  "pande", "panga", "pango", "panzi", "panya", "panua", "papai", "papas",
  "parua", "pasha", "pasua", "patia", "pazia", "penda", "pengo", "penya", "penzi",
  "pepea", "picha", "pigia", "pinga", "pikia", "pimia", "pinda", "pingu", "pinza",
  "pisha", "pitia", "pokea", "pokoa", "pombe", "ponda", "ponya", "ponzo",
  "pooza", "posho", "potea", "potoa", "pumba", "pumua", "punda", "punde",
  "punga", "pungu", "punja", "punje", "pweza", "radhi", "randa", "rarua",
  "rauka", "redio", "remba", "rinda", "ringa", "rithi", "rudia", "rufaa",
  "rukia", "saini", "safia", "salia", "saumu", "sauti", "saza", "shaba",
  "shaka", "shani", "shati", "shiba", "shida", "shika", "shina", "shinda",
  "shoka", "shona", "shoto", "shuka", "shule", "shuta", "sifia", "sikia",
  "simba", "sinia", "soksi", "songa", "suala", "suuza", "swala", "swali",
  "taabu", "tabia", "taifa", "tajia", "takia", "tangi", "tangu", "taulo",
  "tausi", "tembo", "temea", "tende", "tenda", "tendo", "teuzi", "tibua", "tifua",
  "topea", "treni", "tufai", "tulia", "tumbo", "tumia", "tunda", "twiga",
  "ubani", "udaku", "ugali", "ugoro", "uhuru", "ukame", "ukoko", "ukoma",
  "ukuta", "ulimi", "umeme", "unene", "upana", "upepo", "upesi", "urefu",
  "usafi", "usiku", "utamu", "uongo", "uvumi", "uwazi", "uwezo", "uyoga",
  "uzima", "uzito", "uzuri", "valia", "video", "vifaa", "vikao", "vilia",
  "visha", "vizia", "vulia", "vuma", "vumbi", "vuna", "vunda", "vunja",
  "vutia", "wajia", "wakia", "wania", "wanja", "washa", "wasia", "wazia",
  "wazee", "wekea", "wembe", "wimbi", "wimbo", "winda", "wingu", "winza",
  "yaani", "zaidi", "zamia", "zeeka", "zibua", "zikwa", "zimia", "zolea",
  "zuia", "zulia", "zuru", "zuzua"
];

